import { useState } from 'react';
import { Link, useLocation, useParams } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { useListMyGroups,useCreateGroup,useJoinGroup,useGetGroup,useListGroupReactions,useCreateGroupReaction,getListMyGroupsQueryKey,getGetGroupQueryKey,getListGroupReactionsQueryKey } from '@workspace/api-client-react';
import { toast } from 'sonner';
import { Users, ArrowLeft, Copy, Heart, Plus } from 'lucide-react';
import { PageHead, SectionTitle, Field, Modal, Empty, Loading, ErrorBlock, AddButton, dateToday, arDate } from '@/components/journey-ui';
export function GroupsPage(){
  const q=useListMyGroups(),create=useCreateGroup(),join=useJoinGroup(),qc=useQueryClient(),[,navigate]=useLocation();
  const [mode,setMode]=useState<'create'|'join'|null>(null),[name,setName]=useState(''),[goal,setGoal]=useState(''),[start,setStart]=useState(dateToday()),[end,setEnd]=useState(''),[code,setCode]=useState('');
  const refresh=()=>qc.invalidateQueries({queryKey:getListMyGroupsQueryKey()});
  return <><PageHead overline="الطريق أجمل مع رفقة" title="المجموعات" desc="تحديات صغيرة تجمعكم على هدف واحد. شجّع رفاقك، من دون ضجيج." action={<div className="flex gap-2"><button className="btn btn-light" onClick={()=>setMode('join')}>انضم برمز</button><AddButton onClick={()=>setMode('create')} label="تحدٍ جديد"/></div>}/>{q.isLoading?<Loading/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:!q.data?.length?<Empty title="ما زال الطريق ينتظر رفاقه" desc="ابدأ تحديًا مع من تحب، أو انضم إلى تحدٍ بدعوة." action={<AddButton onClick={()=>setMode('create')} label="أنشئ تحديًا"/>}/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{q.data.map((g,i)=><Link href={`/groups/${g.id}`} key={g.id} className="paper rounded-[22px] p-6 hover:-translate-y-1 transition-transform rise" style={{animationDelay:`${i*55}ms`}}><div className="w-12 h-12 rounded-xl bg-[#e5ece0] flex items-center justify-center text-[#285b48] mb-5"><Users size={24}/></div><h3 className="text-xl font-bold">{g.name}</h3><p className="muted text-sm leading-7 mt-2 min-h-12">{g.goalDescription}</p><div className="border-t border-[#eee4d4] pt-4 mt-5 flex justify-between text-sm"><span>{g.memberCount} رفيق</span><span className="text-[#27614c] font-bold flex items-center gap-1">ادخل التحدي <ArrowLeft size={15}/></span></div></Link>)}</div>}
    {mode&&<Modal title={mode==='create'?'تحدٍ جديد':'انضم إلى رفاقك'} onClose={()=>setMode(null)}>{mode==='join'?<form onSubmit={e=>{e.preventDefault();join.mutate({data:{inviteCode:code.trim()}},{onSuccess:g=>{refresh();setMode(null);navigate(`/groups/${g.id}`);toast.success('أهلًا بك بين الرفاق')},onError:()=>toast.error('رمز الدعوة غير صحيح أو تعذّر الانضمام')})}}><Field label="رمز الدعوة"><input className="field" required value={code} onChange={e=>setCode(e.target.value)} placeholder="اكتب الرمز الذي وصلك"/></Field><button className="btn" disabled={join.isPending}>الانضمام إلى التحدي</button></form>:<form onSubmit={e=>{e.preventDefault();create.mutate({data:{name,goalDescription:goal,startDate:start,endDate:end||undefined}},{onSuccess:g=>{refresh();setMode(null);navigate(`/groups/${g.id}`);toast.success('بدأ تحديكم!')},onError:()=>toast.error('تعذّر إنشاء التحدي')})}}><Field label="اسم التحدي"><input className="field" required value={name} onChange={e=>setName(e.target.value)} placeholder="مثل: شهر من الحركة"/></Field><Field label="ما الهدف المشترك؟"><textarea className="field" required value={goal} onChange={e=>setGoal(e.target.value)} placeholder="صفوا ما تريدون تحقيقه معًا"/></Field><div className="grid grid-cols-2 gap-3"><Field label="البداية"><input type="date" className="field" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="النهاية (اختياري)"><input type="date" className="field" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><button className="btn" disabled={create.isPending}>بدء التحدي</button></form>}</Modal>}
  </>;
}
export function GroupDetailPage(){
  const {groupId}=useParams<{groupId:string}>(),id=Number(groupId);const group=useGetGroup(id,{query:{enabled:!!id,queryKey:getGetGroupQueryKey(id)}}),reactions=useListGroupReactions(id,{query:{enabled:!!id,queryKey:getListGroupReactionsQueryKey(id)}}),react=useCreateGroupReaction(),qc=useQueryClient();const [cheering,setCheering]=useState<string|null>(null);
  if(group.isLoading)return <Loading/>;if(group.isError||!group.data)return <ErrorBlock retry={()=>group.refetch()}/>;const g=group.data;
  const cheer=(toUserId:string,emoji:string)=>react.mutate({groupId:id,data:{toUserId,emoji}},{onSuccess:()=>{qc.invalidateQueries({queryKey:getListGroupReactionsQueryKey(id)});setCheering(null);toast.success('وصل تشجيعك!')},onError:()=>toast.error('تعذّر إرسال التشجيع')});
  return <><Link href="/groups" className="text-sm muted flex items-center gap-2 mb-6">العودة للمجموعات <ArrowLeft size={15}/></Link><PageHead overline="تحدٍ يجمعكم" title={g.name} desc={g.goalDescription}/><div className="grid lg:grid-cols-[1fr_.5fr] gap-6"><div><div className="paper rounded-[24px] p-6 md:p-8"><SectionTitle label="كل خطوة تُلهم الأخرى" title="تقدّم الرفاق"/><div className="space-y-3">{g.members.slice().sort((a,b)=>b.progressCount-a.progressCount).map((m,i)=><div key={m.userId} className="flex items-center gap-3 panel rounded-xl p-3"><span className="w-7 text-center font-bold text-[#ac795a]">{i+1}</span><span className="w-11 h-11 rounded-full bg-[#e1dbc6] flex items-center justify-center text-2xl">{m.avatarEmoji}</span><div className="flex-1 min-w-0"><strong>{m.displayName}{m.isMe?' (أنت)':''}</strong><div className="muted text-xs">{m.progressCount} خطوات</div></div><div className="relative"><button className="btn btn-light !px-3 !py-2" aria-label={`تشجيع ${m.displayName}`} onClick={()=>setCheering(cheering===m.userId?null:m.userId)}><Heart size={16}/></button>{cheering===m.userId&&<div className="absolute top-full left-0 z-10 mt-2 paper shadow-lg rounded-xl p-2 flex gap-1">{['👏','💪','🌟','❤️'].map(emoji=><button key={emoji} className="text-xl p-1 hover:scale-125 transition-transform" onClick={()=>cheer(m.userId,emoji)}>{emoji}</button>)}</div>}</div></div>)}</div></div></div><aside className="space-y-5"><div className="rounded-[22px] bg-[#214e43] p-6 text-[#fff9e9]"><div className="text-sm text-[#c4dac8]">ادعُ رفاقك بهذا الرمز</div><div className="flex items-center justify-between gap-3 mt-3"><strong className="text-2xl tracking-[.15em]" dir="ltr">{g.inviteCode}</strong><button className="btn !bg-[#e5b37b] !border-[#e5b37b] !text-[#214e43] !p-2" onClick={()=>navigator.clipboard.writeText(g.inviteCode).then(()=>toast.success('نُسخ رمز الدعوة')).catch(()=>toast.error('تعذّر نسخ الرمز'))} aria-label="نسخ رمز الدعوة"><Copy size={17}/></button></div><div className="text-xs text-[#b6cfc0] mt-5">بدأ في {arDate(g.startDate)}{g.endDate?` · حتى ${arDate(g.endDate)}`:''}</div></div><div className="paper rounded-[22px] p-6"><SectionTitle label="كلمات بلا ضجيج" title="التشجيع الأخير"/>{reactions.isLoading?<div className="skeleton h-20"/>:reactions.data?.length?<div className="space-y-3">{reactions.data.slice(-8).reverse().map(r=><div key={r.id} className="flex justify-between text-sm border-b border-[#eee6d9] py-2"><span>{r.fromDisplayName} أرسل تشجيعًا</span><span className="text-xl">{r.emoji}</span></div>)}</div>:<p className="muted text-sm">كن أول من يرسل كلمة تشجيع.</p>}</div></aside></div></>;
}