import { useState } from 'react';
import { Link, useParams } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { useListHabits, useUpdateHabit, useDeleteHabit, useGetHabit, useGetDashboardToday, useListHabitCheckins, useCreateCheckin, useUpdateCheckinReflection, useGetHabitAdaptation, useRecoverStreak, useListTimeEntries, useCreateTimeEntry, useListRewards, getListHabitsQueryKey, getGetHabitQueryKey, getListHabitCheckinsQueryKey, getGetHabitAdaptationQueryKey, getGetDashboardTodayQueryKey, getGetDashboardCalendarQueryKey, getGetWalletQueryKey, getListTimeEntriesQueryKey, type Habit, type CheckinReflectionMissedReason, type CheckinInputDifficulty, type User } from '@workspace/api-client-react';
import { toast } from 'sonner';
import { ArrowLeft, Flame, Coins, Trash2, Pencil, Plus, Check, RotateCcw, Sparkles } from 'lucide-react';
import { PageHead, SectionTitle, Field, Modal, Empty, Loading, ErrorBlock, AddButton, categories, dateToday as localDateToday, arDate } from '@/components/journey-ui';
import { HabitPlanForm, unitName } from '@/components/habit-plan-form';

const reasons: [Exclude<CheckinReflectionMissedReason,null>|'other',string][]=[['too_difficult','كانت صعبة'],['no_time','لم أجد وقتًا'],['forgot','نسيت'],['lost_motivation','فقدت الحماس'],['unexpected','حدث أمر غير متوقع'],['other','سبب آخر']];
const difficulties:[CheckinInputDifficulty,string][]=[['easy','😊 سهلة'],['normal','🙂 عادية'],['hard','😓 صعبة'],['very_hard','🥵 صعبة جدًا']];
const dateBefore=(days:number,timezone:string)=>{const d=new Date(`${localDateToday(timezone)}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10)};
const status=(h:Habit,value:number,targetCompleted:boolean)=>h.goalType==='quit'?(value<=(h.successLimitValue??h.targetValue)?'ضمن الحد، خطوة ناجحة':'يوم للملاحظة'):targetCompleted?'بلغت الهدف':value>=(h.minimumValue??h.targetValue)?'الحد الأدنى نجح':'خطوة صغيرة';

export function HabitsPage(){
  const q=useListHabits(),update=useUpdateHabit(),remove=useDeleteHabit(),qc=useQueryClient();
  const [form,setForm]=useState<Habit|true|null>(null),[filter,setFilter]=useState<'all'|'active'|'inactive'>('all');
  const refresh=()=>{qc.invalidateQueries({queryKey:getListHabitsQueryKey()});qc.invalidateQueries({queryKey:getGetDashboardTodayQueryKey()})};
  const shown=q.data?.filter(h=>filter==='all'||h.isActive===(filter==='active'))||[];
  return <><PageHead overline="خطوات على الطريق" title="عاداتي" desc="ليست سباقًا مع أحد. كل عادة هنا وعد صغير لنفسك." action={<AddButton onClick={()=>setForm(true)} label="عادة جديدة"/>}/>
    <div className="flex gap-2 mb-6">{([['all','الكل'],['active','النشطة'],['inactive','المتوقفة']] as const).map(([v,t])=><button key={v} className={`px-4 py-2 rounded-full text-sm font-semibold ${filter===v?'bg-[#245448] text-white':'bg-[#eae4d5]'}`} onClick={()=>setFilter(v)}>{t}</button>)}</div>
    {q.isLoading?<Loading/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:!shown.length?<Empty title={q.data?.length?'لا عادات في هذا التصنيف':'هنا تبدأ الحكاية'} desc="أضف عادة صغيرة تريد أن ترافقك في رحلتك." action={<AddButton onClick={()=>setForm(true)} label="أضف عادة"/>}/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{shown.map((h,i)=><div key={h.id} className="paper rounded-[22px] p-6 rise flex flex-col" style={{animationDelay:`${i*55}ms`}}><div className="flex justify-between"><div className="w-14 h-14 rounded-2xl bg-[#e9eddf] flex items-center justify-center text-3xl">{h.emoji}</div><span className="badge h-fit">{h.isActive?'نشطة':'متوقفة'}</span></div><div className="mt-5 eyebrow">{categories[h.category]}</div><Link href={`/habits/${h.id}`} className="text-xl font-bold mt-1 hover:text-[#b66f52]">{h.title}</Link><div className="muted text-sm mt-2">{h.goalType==='quit'?`المعتاد ${h.baselineValue??'—'} · النجاح عند ${h.successLimitValue??h.targetValue} أو أقل`:`الهدف ${h.targetValue} · الحد الأدنى ${h.minimumValue??h.targetValue} · المزدحم ${h.busyDayValue??'—'}`} {unitName(h.unit)}</div><div className="border-t border-[#e8dfce] mt-auto pt-4 flex justify-between items-center gap-2"><span className="flex gap-1 items-center text-[#b67554] font-bold text-sm"><Flame size={16}/>{h.currentStreak} أيام متتالية</span><div className="flex gap-1"><button className="btn btn-ghost !p-2" aria-label="تعديل العادة" onClick={()=>setForm(h)}><Pencil size={16}/></button><button className="btn btn-ghost !p-2" aria-label={h.isActive?'إيقاف العادة':'إعادة تنشيط العادة'} onClick={()=>update.mutate({habitId:h.id,data:{isActive:!h.isActive}},{onSuccess:()=>{refresh();toast.success(h.isActive?'توقفت مؤقتًا':'عادت إلى الطريق')},onError:()=>toast.error('تعذّر تغيير الحالة')})}><RotateCcw size={16}/></button><button className="btn btn-ghost !p-2 !text-[#b96355]" aria-label="حذف العادة" onClick={()=>{if(confirm('هل تريد حذف هذه العادة نهائيًا؟'))remove.mutate({habitId:h.id},{onSuccess:()=>{refresh();toast.success('حُذفت العادة')},onError:()=>toast.error('تعذّر الحذف')})}}><Trash2 size={16}/></button></div></div></div>)}</div>}
    {form&&<Modal title={form===true?'عادة جديدة على الطريق':'تعديل العادة'} onClose={()=>setForm(null)}><HabitPlanForm habit={form===true?undefined:form} onSaved={()=>setForm(null)}/></Modal>}
  </>;
}

export function HabitDetailPage({user}: {user:User}){
   const dashboard=useGetDashboardToday();
   const dateToday=()=>dashboard.data?.date?.slice(0,10)??localDateToday(user.timezone);
  const {habitId}=useParams<{habitId:string}>(),id=Number(habitId),qc=useQueryClient();
  const habit=useGetHabit(id,{query:{enabled:!!id,queryKey:getGetHabitQueryKey(id)}});
  const checks=useListHabitCheckins({habitId:id},{query:{enabled:!!id,queryKey:getListHabitCheckinsQueryKey({habitId:id})}});
  const adaptation=useGetHabitAdaptation(id,{query:{enabled:!!id,queryKey:getGetHabitAdaptationQueryKey(id)}});
  const times=useListTimeEntries({habitId:id},{query:{enabled:!!id,queryKey:getListTimeEntriesQueryKey({habitId:id})}});
  const rewards=useListRewards();
  const check=useCreateCheckin(),reflect=useUpdateCheckinReflection(),update=useUpdateHabit(),recover=useRecoverStreak(),addTime=useCreateTimeEntry();
  const [value,setValue]=useState<number|null>(null),[note,setNote]=useState(''),[mood,setMood]=useState(3),[completedDate,setCompletedDate]=useState<string|null>(null);
   const [missDate,setMissDate]=useState(dateBefore(1,user.timezone)),[reason,setReason]=useState<(typeof reasons)[number][0]>('no_time'),[missNote,setMissNote]=useState('');
  const [offer,setOffer]=useState(false),[editOffer,setEditOffer]=useState(false),[offerTarget,setOfferTarget]=useState(1),[offerMinimum,setOfferMinimum]=useState(1);
  const [timeOpen,setTimeOpen]=useState(false),[mins,setMins]=useState(25),[timeNote,setTimeNote]=useState('');
   const h=habit.data,todayCheck=checks.data?.find(c=>c.date.slice(0,10)===dateToday());
  const refresh=()=>{qc.invalidateQueries({queryKey:getGetHabitQueryKey(id)});qc.invalidateQueries({queryKey:getListHabitCheckinsQueryKey({habitId:id})});qc.invalidateQueries({queryKey:getGetHabitAdaptationQueryKey(id)});qc.invalidateQueries({queryKey:getListHabitsQueryKey()});qc.invalidateQueries({queryKey:getGetDashboardTodayQueryKey()});qc.invalidateQueries({queryKey:getGetDashboardCalendarQueryKey({month:dateToday().slice(0,7)})});qc.invalidateQueries({queryKey:getGetWalletQueryKey()})};
  if(habit.isLoading)return <Loading/>;if(habit.isError||!h)return <ErrorBlock retry={()=>habit.refetch()}/>;
  const measured=value??h.targetValue;
  const logToday=(e:React.FormEvent)=>{e.preventDefault();if(measured<0||!Number.isFinite(measured)){toast.error('اكتب عددًا صالحًا');return}check.mutate({habitId:id,data:{date:dateToday(),completed:true,value:measured}},{onSuccess:r=>{refresh();setCompletedDate(r.date);toast.success(r.completed?`${status(h,measured,r.targetCompleted)} · +${r.coinsEarned} عملة`:'سجّلنا خطوتك كما هي، وغدًا فرصة أخرى')},onError:()=>toast.error('تعذّر تسجيل اليوم')})};
  const saveDifficulty=(difficulty:CheckinInputDifficulty)=>{if(!completedDate)return;reflect.mutate({habitId:id,date:completedDate,data:{difficulty,note:note.trim()||null,moodRating:mood}},{onSuccess:()=>{refresh();setCompletedDate(null);setNote('');toast.success('حفظنا إحساسك بهذا اليوم')},onError:()=>toast.error('تعذّر حفظ انعكاس يومك؛ حاول مجددًا')})};
  const saveMiss=async(e:React.FormEvent)=>{e.preventDefault();if(missDate>dateToday()){toast.error('اختر يومًا مضى');return}if(checks.data?.find(c=>c.date.slice(0,10)===missDate)?.completed){toast.error('هذا اليوم محفوظ كخطوة ناجحة. اختر يومًا فاتك.');return}if(reason==='other'&&!missNote.trim()){toast.error('اكتب سببك في الملاحظة');return}try{if(!checks.data?.some(c=>c.date.slice(0,10)===missDate))await check.mutateAsync({habitId:id,data:{date:missDate,completed:false}});await reflect.mutateAsync({habitId:id,date:missDate,data:{missedReason:reason,note:missNote.trim()||null}});refresh();toast.success('شكرًا لملاحظتك. لا حكم على اليوم الذي فات.')}catch{refresh();toast.error('تعذّر حفظ السبب؛ حاول مجددًا')}};
  const applyOffer=async()=>{const a=adaptation.data;if(!a)return;if(h.targetValue!==a.expectedTargetValue||(h.minimumValue??h.targetValue)!==a.expectedMinimumValue){setOffer(false);toast.error('تغيّرت قيم العادة. حمّل اقتراحًا جديدًا.');habit.refetch();adaptation.refetch();return}if(offerTarget<=0||offerMinimum<=0||offerMinimum>offerTarget){toast.error('اجعل الحد الأدنى أكبر من صفر وأقل من الهدف');return}try{const r=await update.mutateAsync({habitId:id,data:{targetValue:offerTarget,minimumValue:offerMinimum,expectedTargetValue:a.expectedTargetValue,expectedMinimumValue:a.expectedMinimumValue}});qc.setQueryData(getGetHabitQueryKey(id),r);refresh();setOffer(false);toast.success('تغيّر الهدف باختيارك')}catch(e){if(e&&typeof e==='object'&&'status' in e&&e.status===409){setOffer(false);habit.refetch();adaptation.refetch();toast.error('تغيّر الهدف من مكان آخر؛ اطلب اقتراحًا حديثًا')}else toast.error('لم نحفظ التغيير. اقتراحك ما زال هنا.')}};
  const successful=checks.data?.filter(c=>c.completed).length||0,targetDays=checks.data?.filter(c=>c.targetCompleted).length||0,earned=checks.data?.reduce((n,c)=>n+c.coinsEarned,0)||0;
  return <><Link href="/habits" className="text-sm muted flex items-center gap-2 mb-6 hover:text-[#245448]">العودة إلى عاداتي <ArrowLeft size={15}/></Link><PageHead overline={categories[h.category]} title={`${h.emoji} ${h.title}`} desc="كل مرة تعود فيها، تكتب خطوة جديدة. حتى الأيام غير المثالية جزء من الطريق."/>
    <div className="grid lg:grid-cols-[1fr_.76fr] gap-6"><div className="space-y-6">
      <div className="paper rounded-[24px] p-6 md:p-8"><SectionTitle label="لحظة اليوم" title={todayCheck?'خطوة اليوم مسجّلة':'سجّل ما فعلته فعلًا'}/>
        {todayCheck?<div className="rounded-2xl bg-[#e7efe3] p-5"><strong>{status(h,todayCheck.value??0,todayCheck.targetCompleted)}</strong><p className="muted text-sm mt-1">سجّلت {todayCheck.value??0} {unitName(h.unit)}. يومك محفوظ كما هو.</p>{!todayCheck.difficulty&&<button className="underline text-sm mt-3" onClick={()=>setCompletedDate(todayCheck.date)}>كيف كانت هذه الخطوة؟</button>}</div>:<form onSubmit={logToday}><p className="muted mb-5">{h.goalType==='quit'?`كم مرة حدث السلوك اليوم؟ النجاح عند ${h.successLimitValue??h.targetValue} أو أقل.`:`الهدف ${h.targetValue}، والحد الأدنى ${h.minimumValue??h.targetValue} ${unitName(h.unit)}. سجّل ما فعلته دون ضغط.`}</p><Field label={`ما أنجزته (${unitName(h.unit)})`}><input data-testid="input-checkin-value" type="number" min="0" className="field" value={measured} onChange={e=>setValue(Number(e.target.value))}/></Field>{h.goalType==='build'&&h.busyDayValue&&<button type="button" className="text-sm underline text-[#245448] mb-5" onClick={()=>setValue(h.busyDayValue!)}>يومي مزدحم: سأجرّب {h.busyDayValue} {unitName(h.unit)}</button>}<div><button disabled={check.isPending} className="btn btn-coral !px-7"><Check size={17}/>{check.isPending?'نسجّل خطوتك…':'حفظ خطوة اليوم'}</button></div></form>}
        {completedDate&&<div className="mt-5 rounded-2xl bg-[#f3ead9] p-5"><h3 className="font-bold">بعد أن أنجزت، كيف كانت؟</h3><p className="muted text-sm mt-1">اختر الأقرب. الملاحظة اختيارية.</p><div className="flex flex-wrap gap-2 my-4">{difficulties.map(([v,label])=><button type="button" key={v} disabled={reflect.isPending} className="rounded-xl border border-[#d7cbb8] bg-[#fff9ed] px-3 py-2 hover:bg-[#dfebdd]" onClick={()=>saveDifficulty(v)}>{label}</button>)}</div><Field label="ملاحظة صغيرة (اختياري)"><textarea className="field" value={note} onChange={e=>setNote(e.target.value)} placeholder="ما الذي جعلها أسهل أو أصعب؟"/></Field><div className="flex items-center gap-3"><span className="text-sm">مزاجك</span>{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setMood(n)} className={`w-8 h-8 rounded-full border text-sm ${mood===n?'bg-[#245448] text-white':'bg-[#fff9ed]'}`}>{n}</button>)}</div><button className="text-sm underline mt-4" onClick={()=>setCompletedDate(null)}>ليس الآن</button></div>}
      </div>
      <div className="paper rounded-[24px] p-6"><SectionTitle label="مساحة بلا أحكام" title="عن يوم لم يسر كما أردت"/><p className="muted text-sm mb-4">إذا فاتك يوم، أخبرنا لماذا. لن نغيّر هدفك دون إذنك.</p><form onSubmit={saveMiss}><div className="grid sm:grid-cols-2 gap-3"><Field label="اليوم"><input type="date" className="field" max={dateToday()} value={missDate} onChange={e=>setMissDate(e.target.value)} required/></Field><Field label="ما الذي حدث؟"><select className="field" value={reason} onChange={e=>setReason(e.target.value as typeof reason)}>{reasons.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></Field></div><Field label="ملاحظة (اختياري)"><textarea className="field" value={missNote} onChange={e=>setMissNote(e.target.value)} placeholder="ما الذي كان سيجعلها أيسر؟"/></Field><button className="btn btn-light" disabled={check.isPending||reflect.isPending}>حفظ تأمّل اليوم</button></form></div>
      <div className="paper rounded-[24px] p-6"><SectionTitle label="الأثر المتراكم" title="سجل الأيام"/>{checks.isLoading?<Loading/>:checks.isError?<ErrorBlock retry={()=>checks.refetch()}/>:!checks.data?.length?<Empty title="لم تُكتب أول صفحة بعد" desc="سجّل أول خطوة لتراها هنا."/>:<div className="space-y-1">{checks.data.slice().reverse().slice(0,12).map(c=><div key={c.id} className="flex items-center justify-between gap-3 border-b border-[#eee6d8] py-3"><div><strong>{arDate(c.date)}</strong><p className="text-sm muted">{c.completed?status(h,c.value??0,c.targetCompleted):'يوم للتعلّم'} · {c.value??0} {unitName(h.unit)}{c.note?` · ${c.note}`:''}</p></div><span className="badge whitespace-nowrap">+{c.coinsEarned} عملة</span></div>)}</div>}</div>
    </div><aside className="space-y-6">
      <div className="rounded-[24px] bg-[#214e43] text-[#fff9ed] p-7"><Flame className="text-[#eab87a] mb-5" size={28}/><div className="text-5xl font-black">{h.currentStreak}</div><div className="text-[#c8d8ca] mt-2">أيام متتالية · أطول سلسلة {h.longestStreak}</div><div className="border-t border-[#567a6e] mt-5 pt-4 text-sm leading-8">{h.goalType==='quit'?<><p>المستوى المعتاد: {h.baselineValue??'—'} {unitName(h.unit)}</p><p>حد النجاح: {h.successLimitValue??h.targetValue} {unitName(h.unit)} أو أقل</p></>:<><p>هدف اليوم: {h.targetValue} {unitName(h.unit)}</p><p>الحد الأدنى الناجح: {h.minimumValue??h.targetValue} {unitName(h.unit)}</p><p>اليوم المزدحم: {h.busyDayValue??'—'} {unitName(h.unit)}</p></>}</div>{h.currentStreak===0&&h.longestStreak>0&&<button disabled={recover.isPending} className="btn !bg-[#e9b47a] !text-[#20483f] mt-4" onClick={()=>recover.mutate({habitId:id},{onSuccess:r=>{refresh();toast.success(`عادت السلسلة مقابل ${r.coinsSpent} عملة`)},onError:()=>toast.error('لم نتمكن من استعادة السلسلة')})}><Coins size={16}/> استعادة السلسلة</button>}</div>
      <div className="paper rounded-[24px] p-6"><SectionTitle label="رحلتك بالأرقام" title="الأيام التي حضرت فيها"/>{checks.isLoading?<div className="skeleton h-16"/>:<div className="grid grid-cols-3 gap-2 text-center"><div className="panel p-3 rounded-xl"><b className="text-2xl block">{successful}</b><small>أيام ناجحة</small></div><div className="panel p-3 rounded-xl"><b className="text-2xl block">{targetDays}</b><small>بلغت الهدف</small></div><div className="panel p-3 rounded-xl"><b className="text-2xl block">{earned}</b><small>عملة كسبتها</small></div></div>}{rewards.data?.filter(r=>r.habitId===id).map(r=><p key={r.id} className="text-sm mt-3">{r.emoji} {r.title} · {r.isRedeemed?'حصلت عليها':`${r.coinCost} عملة`}</p>)}</div>
      <div className="paper rounded-[24px] p-6"><SectionTitle label="تعديل بإذنك فقط" title="بداية تناسب إيقاعك"/>{adaptation.isLoading?<div className="skeleton h-20"/>:adaptation.isError?<ErrorBlock retry={()=>adaptation.refetch()}/>:<><p className="muted text-sm leading-7">{adaptation.data?.coachMessage||'حين تتراكم خطواتك، يمكننا اقتراح تعديل يناسبك.'}</p>{adaptation.data?.missedDays? <p className="text-xs muted mt-2">{adaptation.data.missedDays} أيام فاتتك في السجل. لا بأس بالعودة.</p>:null}{checks.data?.some(c=>c.missedReason==='no_time')&&h.busyDayValue&&<p className="text-sm mt-3">لم تجد وقتًا؟ خطة اليوم المزدحم: {h.busyDayValue} {unitName(h.unit)} فقط.</p>}{checks.data?.some(c=>c.missedReason==='forgot')&&<p className="text-sm mt-3">إن نسيت، جرّب ربط العادة بشيء تفعله أصلًا، مثل ما بعد الفطور.</p>}{adaptation.data?.suggestion&&h.goalType==='build'&&(adaptation.data.targetValue!==h.targetValue||adaptation.data.minimumValue!==(h.minimumValue??h.targetValue))&&<>{!offer?<div className="flex flex-wrap gap-2 mt-4"><button className="btn btn-light" onClick={()=>{setOfferTarget(adaptation.data!.targetValue);setOfferMinimum(adaptation.data!.minimumValue);setOffer(true);setEditOffer(false)}}><Sparkles size={15}/> انظر إلى الاقتراح</button><button className="text-sm underline" onClick={()=>toast.info('هدفك بقي كما هو')}>أبقي هدفي</button></div>:<div className="panel rounded-xl p-4 mt-4 text-sm"><p>المقترح: {adaptation.data.targetValue} {unitName(h.unit)}، والحد الأدنى {adaptation.data.minimumValue}. لا شيء يتغير حتى تختار.</p>{editOffer&&<div className="grid grid-cols-2 gap-2 mt-3"><Field label="الهدف"><input className="field" type="number" min="1" value={offerTarget} onChange={e=>setOfferTarget(Number(e.target.value))}/></Field><Field label="الحد الأدنى"><input className="field" type="number" min="1" value={offerMinimum} onChange={e=>setOfferMinimum(Number(e.target.value))}/></Field></div>}<div className="flex flex-wrap gap-2 mt-4"><button className="btn" disabled={update.isPending} onClick={applyOffer}>قبول {editOffer?'تعديلي':'الاقتراح'}</button><button className="btn btn-light" onClick={()=>setEditOffer(true)}>تعديل</button><button className="text-sm underline" onClick={()=>{setOffer(false);toast.info('لم نغيّر هدفك')}}>الإبقاء على هدفي</button></div></div>}</>}</>}</div>
      <div className="paper rounded-[24px] p-6"><SectionTitle label="محطات صغيرة" title="معالم الطريق"/>{h.milestones.length?<div className="space-y-4">{h.milestones.map((m,i)=><div key={i} className="flex gap-3"><span className="w-7 h-7 rounded-full bg-[#e8b87c] text-[#245448] flex items-center justify-center text-xs font-bold shrink-0">{i+1}</span><div><strong>{m.title}</strong><p className="text-sm muted">{m.description} · الهدف {m.targetValue}</p></div></div>)}</div>:<p className="muted text-sm">ستظهر محطاتك هنا حين تضيفها لعادتك.</p>}</div>
      <div className="paper rounded-[24px] p-6"><SectionTitle label="وقت تهديه لنفسك" title="سجل الوقت" action={<button onClick={()=>setTimeOpen(true)} aria-label="إضافة وقت" className="btn btn-light !p-2"><Plus size={16}/></button>}/>{times.isLoading?<div className="skeleton h-16"/>:times.data?.length?<div className="space-y-2">{times.data.slice(0,5).map(t=><div className="flex justify-between text-sm border-b border-[#eee7d9] py-2" key={t.id}><span>{t.label}</span><b>{t.durationMinutes} دقيقة</b></div>)}</div>:<p className="muted text-sm">لم تسجّل وقتًا لهذه العادة بعد.</p>}</div>
    </aside></div>
    {timeOpen&&<Modal title="وقت لهذه العادة" onClose={()=>setTimeOpen(false)}><form onSubmit={e=>{e.preventDefault();addTime.mutate({data:{habitId:id,label:h.title,durationMinutes:mins,date:dateToday(),note:timeNote}},{onSuccess:()=>{qc.invalidateQueries({queryKey:getListTimeEntriesQueryKey({habitId:id})});toast.success('حُفظ وقتك');setTimeOpen(false)},onError:()=>toast.error('تعذّر حفظ الوقت')})}}><Field label="الدقائق"><input className="field" type="number" min="1" value={mins} onChange={e=>setMins(Number(e.target.value))}/></Field><Field label="ملاحظة"><textarea className="field" value={timeNote} onChange={e=>setTimeNote(e.target.value)}/></Field><button disabled={addTime.isPending} className="btn">حفظ الوقت</button></form></Modal>}
  </>;
}