import { useState } from 'react';
import { Link, useParams } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { useListHabits,useCreateHabit,useUpdateHabit,useDeleteHabit,useAiBreakdownGoal,useGetHabit,useListHabitCheckins,useCreateCheckin,useRecoverStreak,useAiCheckinFeedback,useAiRelapseRecovery,useListTimeEntries,useCreateTimeEntry,getListHabitsQueryKey,getGetHabitQueryKey,getListHabitCheckinsQueryKey,getGetDashboardTodayQueryKey,getGetWalletQueryKey,getListTimeEntriesQueryKey,type Habit,type HabitInput,type HabitMilestone } from '@workspace/api-client-react';
import { toast } from 'sonner';
import { ArrowLeft, Flame, Sparkles, Coins, Clock3, Trash2, Pencil, Plus, Check, RotateCcw } from 'lucide-react';
import { PageHead, SectionTitle, Field, Modal, Empty, Loading, ErrorBlock, AddButton, categories, dateToday, arDate } from '@/components/journey-ui';

const icons=['📖','🌱','🏃','💧','🧘','🎨','✍️','🎵','☕','🚴'];
const initial:HabitInput={title:'',emoji:'🌱',category:'health',cadence:'daily',unit:'count',targetValue:1,difficulty:'easy',goalType:'build'};
function HabitForm({habit,onClose}: {habit?:Habit,onClose:()=>void}) {
  const [form,setForm]=useState<HabitInput>(habit?{title:habit.title,emoji:habit.emoji,category:habit.category,cadence:habit.cadence,customDays:habit.customDays||undefined,unit:habit.unit,targetValue:habit.targetValue,difficulty:habit.difficulty,goalType:habit.goalType,milestones:habit.milestones}:initial);
  const [milestones,setMilestones]=useState<HabitMilestone[]>(habit?.milestones||[]);
  const create=useCreateHabit(), update=useUpdateHabit(), breakdown=useAiBreakdownGoal(),qc=useQueryClient();
  const set=<K extends keyof HabitInput>(key:K,value:HabitInput[K])=>setForm(f=>({...f,[key]:value}));
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.title.trim()){toast.error('اكتب اسمًا لعادتك');return;}const done=()=>{qc.invalidateQueries({queryKey:getListHabitsQueryKey()});qc.invalidateQueries({queryKey:getGetDashboardTodayQueryKey()});if(habit)qc.invalidateQueries({queryKey:getGetHabitQueryKey(habit.id)});toast.success(habit?'تم تحديث العادة':'خطوة جديدة انضمّت لرحلتك');onClose();};if(habit)update.mutate({habitId:habit.id,data:{...form,milestones}}, {onSuccess:done,onError:()=>toast.error('تعذّر حفظ العادة')});else create.mutate({data:{...form,milestones}}, {onSuccess:done,onError:()=>toast.error('تعذّر إضافة العادة')});};
  return <form onSubmit={submit}>
    <Field label="اسم العادة"><input className="field" value={form.title} onChange={e=>set('title',e.target.value)} placeholder="مثل: قراءة قبل النوم" required/></Field>
    <div className="mb-5"><div className="text-sm font-bold mb-2">رمز العادة</div><div className="flex gap-2 flex-wrap">{icons.map(icon=><button type="button" key={icon} onClick={()=>set('emoji',icon)} className={`rounded-xl w-10 h-10 text-xl border ${form.emoji===icon?'bg-[#eac48c] border-[#bd925a]':'bg-[#f7f1e7] border-[#e5dacb]'}`}>{icon}</button>)}</div></div>
    {!habit&&<Field label="ما نوع هدفك؟"><div className="flex gap-2">{[['build','أريد بناء عادة'],['quit','أريد ترك سلوك']] .map(([v,t])=><button type="button" key={v} onClick={()=>set('goalType',v as HabitInput['goalType'])} className={`flex-1 border rounded-xl p-3 ${form.goalType===v?'bg-[#dfebdd] border-[#3b765c]':'border-[#e3d9c9]'}`}>{t}</button>)}</div></Field>}
    <div className="grid grid-cols-2 gap-3"><Field label="المجال"><select className="field" value={form.category} onChange={e=>set('category',e.target.value as HabitInput['category'])}>{Object.entries(categories).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></Field><Field label="الإيقاع"><select className="field" value={form.cadence} onChange={e=>set('cadence',e.target.value as HabitInput['cadence'])}><option value="daily">يوميًا</option><option value="weekdays">أيام العمل</option><option value="weekly">مرة أسبوعيًا</option><option value="custom_days">أيام أختارها</option></select></Field></div>
    {form.cadence==='custom_days'&&<div className="flex gap-2 mb-4">{['أحد','اثن','ثلا','أرب','خمي','جمع','سبت'].map((x,i)=><button type="button" key={i} onClick={()=>set('customDays',form.customDays?.includes(i)?form.customDays.filter(v=>v!==i):[...(form.customDays||[]),i])} className={`rounded-full w-10 h-10 text-xs border ${form.customDays?.includes(i)?'bg-[#245448] text-white':'bg-[#f7f1e7]'}`}>{x}</button>)}</div>}
    <div className="grid grid-cols-3 gap-3"><Field label="الهدف"><input type="number" min="1" className="field" value={form.targetValue} onChange={e=>set('targetValue',Number(e.target.value))}/></Field><Field label="القياس"><select className="field" value={form.unit} onChange={e=>set('unit',e.target.value as HabitInput['unit'])}><option value="count">مرّة</option><option value="minutes">دقيقة</option><option value="pages">صفحة</option><option value="custom">قيمة</option></select></Field><Field label="الصعوبة"><select className="field" value={form.difficulty} onChange={e=>set('difficulty',e.target.value as HabitInput['difficulty'])}><option value="easy">سهلة</option><option value="medium">متوسطة</option><option value="hard">تحدٍ كبير</option></select></Field></div>
    {form.goalType==='build'&&<div className="panel rounded-xl p-4 mb-5"><button type="button" disabled={!form.title||breakdown.isPending} onClick={()=>breakdown.mutate({data:{title:form.title,category:form.category,goalType:form.goalType,difficulty:form.difficulty,unit:form.unit,targetValue:form.targetValue}}, {onSuccess:r=>{setMilestones(r.milestones);toast.success('اقترح المدرّب محطات لرحلتك');},onError:()=>toast.error('تعذّر اقتراح المحطات')})} className="flex items-center gap-2 text-sm font-bold text-[#245448]"><Sparkles size={17}/>{breakdown.isPending?'المدرّب يفكّر في خطواتك...':'دع المدرّب يقترح محطات صغيرة'}</button>{milestones.length>0&&<div className="mt-3 space-y-2">{milestones.map((m,i)=><div key={i} className="text-sm border-t border-[#d7dece] pt-2">{i+1}. {m.title} — {m.targetValue}</div>)}</div>}</div>}
    <button className="btn w-full" disabled={create.isPending||update.isPending}>{habit?'حفظ التغييرات':'إضافة العادة'} <ArrowLeft size={16}/></button>
  </form>;
}
export function HabitsPage(){
  const q=useListHabits();const update=useUpdateHabit(),remove=useDeleteHabit(),qc=useQueryClient();const [form,setForm]=useState<Habit|true|null>(null);const [filter,setFilter]=useState<'all'|'active'|'inactive'>('all');
  const refresh=()=>{qc.invalidateQueries({queryKey:getListHabitsQueryKey()});qc.invalidateQueries({queryKey:getGetDashboardTodayQueryKey()});};
  return <><PageHead overline="خطوات على الطريق" title="عاداتي" desc="ليست سباقًا مع أحد. كل عادة هنا وعد صغير لنفسك." action={<AddButton onClick={()=>setForm(true)} label="عادة جديدة"/>}/><div className="flex gap-2 mb-6">{[['all','الكل'],['active','النشطة'],['inactive','المتوقفة']].map(([v,t])=><button key={v} className={`px-4 py-2 rounded-full text-sm font-semibold ${filter===v?'bg-[#245448] text-white':'bg-[#eae4d5]'}`} onClick={()=>setFilter(v as typeof filter)}>{t}</button>)}</div>{q.isLoading?<Loading/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:!q.data?.length?<Empty title="هنا تبدأ الحكاية" desc="أضف أول عادة تريد أن ترافقك في رحلتك." action={<AddButton onClick={()=>setForm(true)} label="أضف أول عادة"/>}/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{q.data.filter(h=>filter==='all'||h.isActive===(filter==='active')).map((h,i)=><div key={h.id} className="paper rounded-[22px] p-6 rise flex flex-col" style={{animationDelay:`${i*55}ms`}}><div className="flex justify-between"><div className="w-14 h-14 rounded-2xl bg-[#e9eddf] flex items-center justify-center text-3xl">{h.emoji}</div><span className={`badge h-fit ${!h.isActive?'!bg-[#eee9e1] !text-[#888]' : ''}`}>{h.isActive?'نشطة':'متوقفة'}</span></div><div className="mt-5 eyebrow">{categories[h.category]}</div><Link href={`/habits/${h.id}`} className="text-xl font-bold mt-1 hover:text-[#b66f52]">{h.title}</Link><div className="muted text-sm mt-2">{h.goalType==='quit'?'أبقى على طريقي':'أبني عادة'} · {h.cadence==='daily'?'يوميًا':h.cadence==='weekly'?'أسبوعيًا':'أيام محددة'}</div><div className="border-t border-[#e8dfce] mt-6 pt-4 flex justify-between items-center"><span className="flex gap-1 items-center text-[#b67554] font-bold text-sm"><Flame size={16}/>{h.currentStreak} أيام متتالية</span><div className="flex gap-1"><button className="btn btn-ghost !p-2" aria-label="تعديل العادة" onClick={()=>setForm(h)}><Pencil size={16}/></button><button className="btn btn-ghost !p-2" aria-label={h.isActive?'إيقاف العادة':'إعادة تنشيط العادة'} onClick={()=>update.mutate({habitId:h.id,data:{isActive:!h.isActive}}, {onSuccess:()=>{refresh();toast.success(h.isActive?'أوقفت العادة مؤقتًا':'عادت العادة للطريق')},onError:()=>toast.error('تعذّر تغيير الحالة')})}><RotateCcw size={16}/></button><button className="btn btn-ghost !p-2 !text-[#b96355]" aria-label="حذف العادة" onClick={()=>{if(confirm('هل تريد حذف هذه العادة نهائيًا؟'))remove.mutate({habitId:h.id},{onSuccess:()=>{refresh();toast.success('حُذفت العادة')},onError:()=>toast.error('تعذّر الحذف')})}}><Trash2 size={16}/></button></div></div></div>)}</div>}{form&&<Modal title={form===true?'عادة جديدة على الطريق':'تعديل العادة'} onClose={()=>setForm(null)}><HabitForm habit={form===true?undefined:form} onClose={()=>setForm(null)}/></Modal>}</>;
}
export function HabitDetailPage(){
  const {habitId}=useParams<{habitId:string}>();const id=Number(habitId);const habit=useGetHabit(id,{query:{enabled:!!id,queryKey:getGetHabitQueryKey(id)}});const checks=useListHabitCheckins({habitId:id},{query:{enabled:!!id,queryKey:getListHabitCheckinsQueryKey({habitId:id})}});const times=useListTimeEntries({habitId:id},{query:{enabled:!!id,queryKey:getListTimeEntriesQueryKey({habitId:id})}});
  const check=useCreateCheckin(),recover=useRecoverStreak(),feedback=useAiCheckinFeedback(),relapse=useAiRelapseRecovery(),updateTarget=useUpdateHabit(),addTime=useCreateTimeEntry(),qc=useQueryClient();
  const [value,setValue]=useState<number|null>(null),[mood,setMood]=useState(3),[note,setNote]=useState(''),[timeOpen,setTimeOpen]=useState(false),[mins,setMins]=useState(25),[timeNote,setTimeNote]=useState('');
  const [recoveryOffer,setRecoveryOffer]=useState<{current:number;suggested:number;message:string}|null>(null);
  const [recoveryDecision,setRecoveryDecision]=useState<string|null>(null);
  const h=habit.data; const todayChecked=checks.data?.some(c=>c.date===dateToday());
  const refresh=()=>{qc.invalidateQueries({queryKey:getGetHabitQueryKey(id)});qc.invalidateQueries({queryKey:getListHabitCheckinsQueryKey({habitId:id})});qc.invalidateQueries({queryKey:getGetDashboardTodayQueryKey()});qc.invalidateQueries({queryKey:getGetWalletQueryKey()});};
  if(habit.isLoading)return <Loading/>;if(habit.isError||!h)return <ErrorBlock retry={()=>habit.refetch()}/>;
  const submit=(e:React.FormEvent)=>{e.preventDefault();check.mutate({habitId:id,data:{date:dateToday(),completed:true,value:value??h.targetValue,moodRating:mood,note}}, {onSuccess:r=>{refresh();toast.success(`خطوة موفّقة! +${r.coinsEarned} عملة`);feedback.mutate({data:{habitId:id,completed:true,value:value??h.targetValue,streak:r.newStreak}});},onError:()=>toast.error('تعذّر تسجيل اليوم')})};
  const requestRecovery=()=>{
    setRecoveryOffer(null);setRecoveryDecision(null);
    relapse.mutate({data:{habitId:id,missedDays:1}},{
      onSuccess:r=>setRecoveryOffer({current:r.originalTargetValue,suggested:r.suggestedTargetValue,message:r.message}),
      onError:()=>toast.error('تعذّر طلب اقتراح المدرّب، حاول مجددًا'),
    });
  };
  const acceptRecovery=()=>{
    if(!recoveryOffer || updateTarget.isPending)return;
    if(h.targetValue!==recoveryOffer.current){
      setRecoveryOffer(null);
      toast.error('تغيّر الهدف منذ طلب الاقتراح. اطلب اقتراحًا جديدًا.');
      return;
    }
    updateTarget.mutate({habitId:id,data:{targetValue:recoveryOffer.suggested,expectedTargetValue:recoveryOffer.current}},{
      onSuccess:updated=>{
        qc.setQueryData(getGetHabitQueryKey(id),updated);
        qc.invalidateQueries({queryKey:getListHabitsQueryKey()});
        qc.invalidateQueries({queryKey:getGetDashboardTodayQueryKey()});
        setValue(null);
        setRecoveryOffer(null);
        setRecoveryDecision(`تم تطبيق هدف العودة: ${updated.targetValue} ${updated.unit==='minutes'?'دقيقة':updated.unit==='pages'?'صفحة':'مرّة'}.`);
        toast.success('تم تحديث هدف العادة');
      },
      onError:async error=>{
        if(error && typeof error==='object' && 'status' in error && error.status===409){
          setRecoveryOffer(null);
          toast.info('تغيّر الهدف من مكان آخر. نطلب اقتراحًا جديدًا بناءً على الهدف الحالي.');
          const latest=await habit.refetch();
          if(latest.isError || !latest.data){
            toast.error('تعذّر تحميل الهدف الحالي. حاول طلب اقتراح جديد.');
            return;
          }
          requestRecovery();
          return;
        }
        toast.error('تعذّر تحديث الهدف. لم يتغيّر هدف العادة، حاول مجددًا.');
      },
    });
  };
  return <><Link href="/habits" className="text-sm muted flex items-center gap-2 mb-6 hover:text-[#245448]">العودة إلى عاداتي <ArrowLeft size={15}/></Link><PageHead overline={categories[h.category]} title={`${h.emoji} ${h.title}`} desc={h.goalType==='quit'?'كل يوم تبقى فيه على الطريق هو خطوة تستحق الاحتفاء.':'كل مرة تعود فيها، تتقدّم خطوة جديدة.'}/>
    <div className="grid lg:grid-cols-[1fr_.76fr] gap-6"><div className="space-y-6">
      <div className="paper rounded-[24px] p-6 md:p-8"><SectionTitle label="لحظة اليوم" title={todayChecked?'أنجزت خطوتك اليوم':'سجّل خطوتك'}/>{todayChecked?<div className="flex items-center gap-4 bg-[#e7efe3] rounded-2xl p-6"><div className="w-12 h-12 rounded-full bg-[#31745a] text-white flex items-center justify-center pop"><Check/></div><div><strong>رائع، أنت على الطريق.</strong><p className="muted text-sm">ارجع غدًا لنضيف خطوة أخرى.</p></div></div>:<form onSubmit={submit}><p className="muted mb-5">{h.goalType==='quit'?'هل بقيت على طريقك اليوم؟':'هل خصصت وقتًا لهذه العادة اليوم؟'}</p><Field label={`القيمة (${h.unit==='minutes'?'دقيقة':h.unit==='pages'?'صفحة':'مرّة'})`}><input type="number" min="0" className="field" value={value??h.targetValue} onChange={e=>setValue(Number(e.target.value))}/></Field><div className="mb-5"><div className="font-bold text-sm mb-3">كيف كان شعورك؟</div><div className="flex gap-2">{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setMood(n)} className={`w-10 h-10 rounded-full border font-bold ${mood===n?'bg-[#245448] text-white':'bg-[#f4f0e7]'}`}>{n}</button>)}</div></div><Field label="ملاحظة صغيرة (اختياري)"><textarea className="field min-h-24" value={note} onChange={e=>setNote(e.target.value)} placeholder="ما الذي جعل اليوم مختلفًا؟"/></Field><button disabled={check.isPending} className="btn btn-coral !px-7"><Check size={17}/>{check.isPending?'نسجّل خطوتك...':h.goalType==='quit'?'بقيت على طريقي اليوم':'أنجزت عادتي اليوم'}</button></form>}{feedback.isPending&&<div className="mt-5 panel p-4 rounded-xl text-sm">المدرّب يفكّر في خطوتك...</div>}{feedback.data&&<div className="mt-5 panel p-5 rounded-xl"><div className="eyebrow mb-2">مدرّبك يقول</div>«{feedback.data.message}»</div>}</div>
      <div className="paper rounded-[24px] p-6"><SectionTitle label="الأثر المتراكم" title="سجل الأيام"/>{checks.isLoading?<Loading/>:!checks.data?.length?<Empty title="لم تُكتب أول صفحة بعد" desc="سجّل يومك الأول لترى خطواتك هنا."/>:<div className="space-y-1">{checks.data.slice().reverse().slice(0,12).map(c=><div key={c.id} className="flex items-center justify-between border-b border-[#eee6d8] py-3"><div><strong>{arDate(c.date)}</strong>{c.note&&<p className="text-sm muted">{c.note}</p>}</div><span className="badge">+{c.coinsEarned} عملة</span></div>)}</div>}</div>
    </div><aside className="space-y-6"><div className="rounded-[24px] bg-[#214e43] text-[#fff9ed] p-7"><Flame className="text-[#eab87a] mb-5" size={28}/><div className="text-5xl font-black">{h.currentStreak}</div><div className="text-[#c8d8ca] mt-2">أيام متتالية · أطول سلسلة {h.longestStreak}</div><p className="text-[#c8d8ca] mt-2 text-sm">هدف العادة الحالي: {h.targetValue} {h.unit==='minutes'?'دقيقة':h.unit==='pages'?'صفحة':'مرّة'}</p>{h.currentStreak===0&&h.longestStreak>0&&<div className="mt-5 border-t border-[#567a6e] pt-5"><p className="text-sm mb-3">انقطعت السلسلة؟ يمكنك استعادتها بعملاتك.</p><button disabled={recover.isPending} className="btn !bg-[#e9b47a] !text-[#20483f] !border-[#e9b47a]" onClick={()=>recover.mutate({habitId:id},{onSuccess:r=>{refresh();toast.success(`استعدت السلسلة مقابل ${r.coinsSpent} عملة`)},onError:()=>toast.error('لم نتمكن من استعادة السلسلة')})}><Coins size={16}/> استعادة السلسلة</button><button className="block text-sm underline mt-3" disabled={relapse.isPending||updateTarget.isPending} onClick={requestRecovery}>{relapse.isPending?'المدرّب يفكّر...':'اسأل المدرّب عن بداية جديدة'}</button>{recoveryOffer&&<div className="mt-3 text-sm leading-7"><p>{recoveryOffer.message}</p><p className="mt-2">هدفك الحالي: <strong>{recoveryOffer.current}</strong> · هدف العودة المقترح: <strong>{recoveryOffer.suggested}</strong> {h.unit==='minutes'?'دقيقة':h.unit==='pages'?'صفحة':'مرّة'}</p><div className="flex flex-wrap gap-2 mt-3"><button type="button" className="btn !bg-[#e9b47a] !text-[#20483f] !border-[#e9b47a]" disabled={updateTarget.isPending||recoveryOffer.suggested>=recoveryOffer.current} onClick={acceptRecovery}>{updateTarget.isPending?'نحدّث الهدف...':'تطبيق هدف العودة'}</button><button type="button" className="btn btn-ghost !text-[#fff9ed]" disabled={updateTarget.isPending} onClick={()=>{setRecoveryOffer(null);setRecoveryDecision(`بقي هدفك كما هو: ${h.targetValue}.`);toast.info('أبقينا هدف العادة دون تغيير')}}>الإبقاء على هدفي الحالي</button></div>{recoveryOffer.suggested>=recoveryOffer.current&&<p className="mt-2">هدفك الحالي هو الحد الأدنى بالفعل؛ يمكنك الإبقاء عليه.</p>}</div>}{recoveryDecision&&<p role="status" className="mt-3 text-sm">{recoveryDecision}</p>}</div>}</div>
    <div className="paper rounded-[24px] p-6"><SectionTitle label="محطات صغيرة" title="معالم الطريق"/>{h.milestones.length?<div className="space-y-4">{h.milestones.map((m,i)=><div key={i} className="flex gap-3"><span className="w-7 h-7 rounded-full bg-[#e8b87c] text-[#245448] flex items-center justify-center text-xs font-bold shrink-0">{i+1}</span><div><strong>{m.title}</strong><p className="text-sm muted">{m.description} · الهدف {m.targetValue}</p></div></div>)}</div>:<p className="muted text-sm">ستظهر محطاتك هنا حين تضيفها لعادتك.</p>}</div>
    <div className="paper rounded-[24px] p-6"><SectionTitle label="وقت تهديه لنفسك" title="سجل الوقت" action={<button onClick={()=>setTimeOpen(true)} className="btn btn-light !p-2"><Plus size={16}/></button>}/>{times.isLoading?<div className="skeleton h-16"/>:times.data?.length?<div className="space-y-2">{times.data.slice(0,5).map(t=><div className="flex justify-between text-sm border-b border-[#eee7d9] py-2" key={t.id}><span>{t.label}</span><b>{t.durationMinutes} دقيقة</b></div>)}</div>:<p className="muted text-sm">لم تسجّل وقتًا لهذه العادة بعد.</p>}</div></aside></div>
    {timeOpen&&<Modal title="وقت لهذه العادة" onClose={()=>setTimeOpen(false)}><form onSubmit={e=>{e.preventDefault();addTime.mutate({data:{habitId:id,label:h.title,durationMinutes:mins,date:dateToday(),note:timeNote}},{onSuccess:()=>{qc.invalidateQueries({queryKey:getListTimeEntriesQueryKey({habitId:id})});toast.success('حُفظ وقتك');setTimeOpen(false)},onError:()=>toast.error('تعذّر حفظ الوقت')})}}><Field label="الدقائق"><input className="field" type="number" min="1" value={mins} onChange={e=>setMins(Number(e.target.value))}/></Field><Field label="ملاحظة"><textarea className="field" value={timeNote} onChange={e=>setTimeNote(e.target.value)}/></Field><button className="btn">حفظ الوقت</button></form></Modal>}
  </>;
}