import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useListHabits,useListTimeEntries,useGetTimeEntriesSummary,useCreateTimeEntry,useDeleteTimeEntry,useListMemories,useCreateMemory,useDeleteMemory,getListTimeEntriesQueryKey,getGetTimeEntriesSummaryQueryKey,getListMemoriesQueryKey,type Habit } from '@workspace/api-client-react';
import { usePhotoUpload } from '@/hooks/use-photo-upload';
import { toast } from 'sonner';
import { Clock3, Trash2, Camera, Plus } from 'lucide-react';
import { PageHead, SectionTitle, Field, Modal, Empty, Loading, ErrorBlock, AddButton, dateToday, arDate } from '@/components/journey-ui';

export function TimePage(){
  const [date,setDate]=useState(dateToday()),[open,setOpen]=useState(false),[label,setLabel]=useState(''),[minutes,setMinutes]=useState(25),[habitId,setHabitId]=useState(''),[note,setNote]=useState('');
  const entries=useListTimeEntries({date}),summary=useGetTimeEntriesSummary({date}),habits=useListHabits(),create=useCreateTimeEntry(),remove=useDeleteTimeEntry(),qc=useQueryClient();
  const refresh=()=>{qc.invalidateQueries({queryKey:getListTimeEntriesQueryKey({date})});qc.invalidateQueries({queryKey:getGetTimeEntriesSummaryQueryKey({date})});};
  return <><PageHead overline="ساعات لها معنى" title="وقتي" desc="لاحظ أين تذهب ساعاتك، واحتفِ بالوقت الذي تمنحه لما يهمك." action={<AddButton onClick={()=>setOpen(true)} label="سجّل وقتًا"/>}/><div className="mb-7 max-w-xs"><Field label="اختر يومًا"><input className="field" type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field></div><div className="grid lg:grid-cols-[.7fr_1.3fr] gap-6"><div className="rounded-[24px] bg-[#214e43] text-[#fff9e9] p-8 h-fit"><Clock3 className="text-[#e8b577] mb-8"/><div className="text-5xl font-black">{summary.data?.totalMinutes??0}</div><p className="text-[#c2d6c8] mt-2">دقيقة لنفسك في هذا اليوم</p><div className="border-t border-[#4c7568] mt-8 pt-5 space-y-4">{summary.data?.byHabit.map((x,i)=><div key={i} className="flex justify-between text-sm"><span>{x.label}</span><b>{x.minutes} دقيقة</b></div>)}</div></div><div><SectionTitle label="ما عشته اليوم" title="سجل الأنشطة"/>{entries.isLoading?<Loading/>:entries.isError?<ErrorBlock retry={()=>entries.refetch()}/>:!entries.data?.length?<Empty title="لا وقت مسجّل بعد" desc="حتى الدقائق الصغيرة تستحق أن تُحفظ." action={<AddButton onClick={()=>setOpen(true)} label="سجّل أول نشاط"/>}/>:<div className="space-y-3">{entries.data.map((t,i)=><div key={t.id} className="paper rounded-xl p-5 flex justify-between items-center rise" style={{animationDelay:`${i*55}ms`}}><div><strong>{t.label}</strong><p className="muted text-sm mt-1">{t.note||arDate(t.date)}</p></div><div className="flex items-center gap-3"><span className="badge">{t.durationMinutes} دقيقة</span><button aria-label="حذف الوقت" className="text-[#ad6d59]" onClick={()=>{if(confirm('حذف هذا السجل؟'))remove.mutate({timeEntryId:t.id},{onSuccess:()=>{refresh();toast.success('حُذف السجل')},onError:()=>toast.error('تعذّر الحذف')})}}><Trash2 size={16}/></button></div></div>)}</div>}</div></div>
    {open&&<Modal title="وقت يستحق أن يُحفظ" onClose={()=>setOpen(false)}><form onSubmit={e=>{e.preventDefault();create.mutate({data:{label,durationMinutes:minutes,date,habitId:habitId?Number(habitId):undefined,note}},{onSuccess:()=>{refresh();setOpen(false);setLabel('');setNote('');toast.success('حُفظ وقتك')},onError:()=>toast.error('تعذّر حفظ الوقت')})}}><Field label="بماذا قضيت وقتك؟"><input className="field" required value={label} onChange={e=>setLabel(e.target.value)} placeholder="قراءة، مشي، تعلّم..."/></Field><Field label="المدة بالدقائق"><input type="number" min="1" className="field" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></Field><Field label="عادة مرتبطة (اختياري)"><select className="field" value={habitId} onChange={e=>setHabitId(e.target.value)}><option value="">بلا عادة محددة</option>{habits.data?.map(h=><option key={h.id} value={h.id}>{h.title}</option>)}</select></Field><Field label="ملاحظة (اختياري)"><textarea className="field" value={note} onChange={e=>setNote(e.target.value)}/></Field><button className="btn" disabled={create.isPending}>حفظ الوقت</button></form></Modal>}
  </>;
}

export function MemoriesPage(){
  const q=useListMemories(),habits=useListHabits(),create=useCreateMemory(),remove=useDeleteMemory(),{uploadPhoto}=usePhotoUpload(),qc=useQueryClient();
  const [open,setOpen]=useState(false),[note,setNote]=useState(''),[date,setDate]=useState(dateToday()),[habitId,setHabitId]=useState(''),[photo,setPhoto]=useState<File|null>(null),[uploading,setUploading]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();try{setUploading(true);const photoObjectPath=photo?await uploadPhoto(photo):undefined;await create.mutateAsync({data:{note,date,habitId:habitId?Number(habitId):undefined,photoObjectPath}});qc.invalidateQueries({queryKey:getListMemoriesQueryKey()});toast.success('حُفظت الذكرى');setOpen(false);setNote('');setPhoto(null);}catch{toast.error('لم نتمكن من حفظ الذكرى. جرّب مرة أخرى.')}finally{setUploading(false)}};
  return <><PageHead overline="دفتر الطريق" title="ذكرياتي" desc="بعض الأيام تستحق أكثر من علامة صح. اترك لها كلمة أو صورة." action={<AddButton onClick={()=>setOpen(true)} label="ذكرى جديدة"/>}/>{q.isLoading?<Loading/>:q.isError?<ErrorBlock retry={()=>q.refetch()}/>:!q.data?.length?<Empty title="دفترك ينتظر أول حكاية" desc="التقط لحظة صغيرة اليوم، ودعها تبقى هنا." action={<AddButton onClick={()=>setOpen(true)} label="أضف ذكرى"/>}/>:<div className="columns-1 md:columns-2 xl:columns-3 gap-5">{q.data.map((m,i)=><article key={m.id} className="paper rounded-[22px] overflow-hidden mb-5 break-inside-avoid rise" style={{animationDelay:`${i*65}ms`}}>{m.photoUrl&&<img src={m.photoUrl} alt="صورة من الذكرى" className="w-full max-h-[350px] object-cover"/>}<div className="p-6"><span className="eyebrow">{arDate(m.date)}</span><p className="text-lg leading-8 mt-3 whitespace-pre-wrap">{m.note}</p>{m.habitId&&<span className="badge mt-4">{habits.data?.find((h:Habit)=>h.id===m.habitId)?.title||'عادة من رحلتك'}</span>}<div className="flex justify-end mt-4"><button className="text-[#ad6d59] p-2" aria-label="حذف الذكرى" onClick={()=>{if(confirm('هل تريد حذف هذه الذكرى؟'))remove.mutate({memoryId:m.id},{onSuccess:()=>{qc.invalidateQueries({queryKey:getListMemoriesQueryKey()});toast.success('حُذفت الذكرى')},onError:()=>toast.error('تعذّر حذف الذكرى')})}}><Trash2 size={16}/></button></div></div></article>)}</div>}
    {open&&<Modal title="لحظة تستحق أن تبقى" onClose={()=>setOpen(false)}><form onSubmit={submit}><Field label="ما الذي تريد تذكّره؟"><textarea className="field min-h-32" required value={note} onChange={e=>setNote(e.target.value)} placeholder="اكتب ما حدث، أو كيف شعرت..."/></Field><Field label="التاريخ"><input className="field" type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="عادة مرتبطة (اختياري)"><select className="field" value={habitId} onChange={e=>setHabitId(e.target.value)}><option value="">ذكرى مستقلة</option>{habits.data?.map(h=><option key={h.id} value={h.id}>{h.title}</option>)}</select></Field><label className="block mb-5 border border-dashed border-[#bcc8b8] bg-[#f4f5ea] rounded-xl p-6 text-center cursor-pointer"><Camera className="mx-auto mb-2 text-[#41725e]"/><span className="text-sm font-bold">{photo?photo.name:'أضف صورة لهذه اللحظة (اختياري)'}</span><input className="sr-only" type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><button className="btn w-full" disabled={uploading||create.isPending}><Plus size={17}/>{uploading?'نحفظ لحظتك...':'حفظ الذكرى'}</button></form></Modal>}
  </>;
}