import { Link } from 'wouter';
import { ArrowLeft, Check, Coins, Map, Sparkles, Heart, ArrowUpLeft } from 'lucide-react';

export function Landing() {
  return <div className="min-h-[100dvh] bg-[#f7f1e5] overflow-hidden">
    <header className="max-w-[1240px] mx-auto px-6 md:px-10 h-20 flex items-center justify-between"><Link href="/" className="flex items-center gap-3 text-[#204a40] font-black text-xl" style={{fontFamily:'Cairo'}}><img src={`${import.meta.env.BASE_URL}logo.svg`} className="w-10 h-10" alt="شعار رحلة العادة"/>رحلة العادة</Link><div className="flex items-center gap-2"><Link href="/sign-in" className="btn btn-ghost">دخول</Link><Link href="/sign-up" className="btn !py-2.5">ابدأ الرحلة <ArrowLeft size={16}/></Link></div></header>
    <section className="max-w-[1240px] mx-auto px-6 md:px-10 pt-14 md:pt-20 pb-20 grid lg:grid-cols-[.9fr_1.1fr] gap-12 items-center">
      <div className="page-enter relative z-10"><span className="eyebrow inline-flex items-center gap-2 mb-7"><span className="w-6 h-px bg-[#bf7857]"/> مساحتك الصغيرة للتغيير الكبير</span><h1 className="font-black text-[52px] md:text-[76px] leading-[1.23] tracking-tight max-w-[650px]">ليست قائمة مهام.<br/><span className="text-[#ce7855]">إنها رحلتك.</span></h1><p className="text-[#657b6e] text-lg md:text-xl leading-[2] max-w-[500px] mt-6 mb-9">كل عادة تزرعها، وكل يوم تحاول فيه، يترك أثرًا على الطريق. ابنِ حياة تشبهك خطوة بخطوة.</p><div className="flex flex-wrap gap-3"><Link href="/sign-up" className="btn !px-7 !py-4">ابدأ رحلتك الآن <ArrowLeft size={18}/></Link><a href="#كيف-تعمل" className="btn btn-light !px-7 !py-4">اكتشف كيف تعمل</a></div><p className="text-sm muted mt-7">مساحة خاصة لك. بلا مقارنة، بلا ضغط.</p></div>
      <div className="relative h-[470px] md:h-[570px] rounded-[32px] overflow-hidden bg-[#d5dec7] shadow-[0_30px_80px_#254f3d20]"><img src={`${import.meta.env.BASE_URL}journey-landscape.png`} alt="رسم لطريق متعرج بين الجبال" className="w-full h-full object-cover"/><div className="absolute top-8 right-8 bg-[#fff9e9ed] backdrop-blur rounded-2xl p-4 shadow-lg flex items-center gap-3"><span className="w-10 h-10 rounded-full bg-[#e9ddbc] flex items-center justify-center"><Map size={20}/></span><div><strong className="block text-sm">طريقك يبدأ هنا</strong><small className="muted">كل خطوة تُحتسب</small></div></div><div className="absolute bottom-8 left-8 bg-[#204b40] text-[#fff9e9] rounded-2xl px-5 py-4 flex items-center gap-3 shadow-xl"><Coins className="text-[#f2c77f]"/><div><b className="block">تقدّم يكافئك</b><small className="text-[#c5d9cb]">بالطريقة التي تختارها أنت</small></div></div></div>
    </section>
    <section id="كيف-تعمل" className="bg-[#1f493e] text-[#fff9eb] py-24"><div className="max-w-[1160px] mx-auto px-6 md:px-10"><span className="text-[#e8ad76] text-sm font-bold">ببساطة، وعلى طريقتك</span><h2 className="text-4xl md:text-5xl font-black mt-3 mb-14 max-w-[650px] leading-[1.5]">روتين يومي يستحق أن تعود إليه.</h2><div className="grid md:grid-cols-3 gap-5">{[{n:'01',icon:Check,t:'اختر خطوتك',d:'ابدأ بعادة واحدة تريد أن تبنيها أو تتركها. أنت تحدد إيقاعك وهدفك.'},{n:'02',icon:Map,t:'شاهد الطريق يتشكل',d:'سجّل يومك، وتقدّم بشخصيتك على خريطة رحلتك. ليس هناك يوم بلا معنى.'},{n:'03',icon:Coins,t:'كافئ نفسك حقًا',d:'اكسب عملات مقابل محاولاتك، واستبدلها بمكافآت حقيقية تضعها بنفسك.'}].map((x)=><div key={x.n} className="border-t border-[#6f9181] pt-7 pr-1"><span className="text-[#deac78] text-sm">{x.n}</span><x.icon size={28} className="mt-8 mb-6 text-[#e7b381]"/><h3 className="text-2xl font-bold">{x.t}</h3><p className="text-[#c0d3c5] leading-[1.9] mt-3">{x.d}</p></div>)}</div></div></section>
    <section className="py-24 max-w-[1160px] mx-auto px-6 md:px-10 grid md:grid-cols-2 gap-14 items-center"><div className="paper rounded-[30px] p-8 md:p-12 rotate-[-2deg]"><div className="text-xs font-bold text-[#b47455] mb-6">رسالة من مدرّبك</div><Sparkles size={27} className="text-[#d39064] mb-6"/><p className="text-2xl md:text-3xl leading-[1.8] font-semibold">«الخطوة الصغيرة التي كررتها اليوم أهم من القفزة الكبيرة التي انتظرتها.»</p><div className="border-t border-[#e6dfcf] pt-5 mt-7 text-sm muted">صوت يشبه ما تحتاجه، لا تنبيه آخر تتجاهله.</div></div><div><div className="eyebrow">رفيق يعرف أسلوبك</div><h2 className="text-4xl md:text-5xl font-black leading-[1.5] mt-4">تشجيع يفهمك.<br/>لا كلامًا محفوظًا.</h2><p className="muted text-lg leading-[2] mt-5">اختر مدرّبًا لطيفًا، أو صريحًا يدفعك للأمام، أو محبًا للأرقام. يتبدّل صوته مع اختيارك وتقدّمك.</p></div></section>
    <section className="bg-[#e8dfca] py-24"><div className="max-w-[1160px] mx-auto px-6 md:px-10 grid md:grid-cols-2 gap-12 items-center"><div><div className="eyebrow">أكثر من سجل يومي</div><h2 className="text-4xl md:text-5xl font-black leading-[1.5] mt-4">احتفظ بلحظات<br/>الطريق أيضًا.</h2><p className="muted text-lg leading-[2] mt-5">الوقت الذي منحته لنفسك، الذكريات التي صنعتها، والأشخاص الذين يرافقونك. كل ذلك له مكان هنا.</p></div><div className="grid grid-cols-2 gap-4"><div className="paper rounded-[24px] p-6 mt-10"><Heart className="text-[#d07a58] mb-12"/><h3 className="font-bold text-xl">ذكرياتك</h3><p className="muted text-sm mt-2">صورة وكلمة تحفظان اللحظة.</p></div><div className="paper rounded-[24px] p-6"><ArrowUpLeft className="text-[#d07a58] mb-12"/><h3 className="font-bold text-xl">وقتُك</h3><p className="muted text-sm mt-2">اعرف أين تنمو ساعاتك.</p></div></div></div></section>
    <section className="text-center py-28 px-6"><span className="eyebrow">لا تنتظر اللحظة المثالية</span><h2 className="text-4xl md:text-6xl font-black mt-5 mb-5">ابدأ من حيث أنت.</h2><p className="muted text-lg mb-9">أول خطوة لا تحتاج إلا قرارًا واحدًا.</p><Link href="/sign-up" className="btn !px-9 !py-4">اصنع بداية جديدة <ArrowLeft size={18}/></Link></section>
    <footer className="border-t border-[#ded6c5] max-w-[1160px] mx-auto px-6 py-8 flex justify-between text-sm muted"><span>رحلة العادة</span><span>كل يوم بداية ممكنة.</span></footer>
  </div>;
}