import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useListRewards,useCreateReward,useUpdateReward,useDeleteReward,useRedeemReward,useGetWallet,useListWalletTransactions,useListHabits,useGetJourneyProgress,useGetMyCharacter,useListCharacterCatalog,usePurchaseCharacterItem,useEquipCharacterItem,getListRewardsQueryKey,getGetWalletQueryKey,getListWalletTransactionsQueryKey,getGetCurrentUserQueryKey,getListCharacterCatalogQueryKey,getGetMyCharacterQueryKey,type Reward } from '@workspace/api-client-react';
import { toast } from 'sonner';
import { Coins, Gift, Pencil, Trash2, Check, Lock, MapPin, Sparkles } from 'lucide-react';
import { PageHead, SectionTitle, Field, Modal, Empty, Loading, ErrorBlock, AddButton, arDate } from '@/components/journey-ui';

const rewardIcons=['🎁','☕','🎬','📚','🌷','🍰','🎟️','🧳'];
export function RewardsPage(){
  const rewards=useListRewards(),wallet=useGetWallet(),transactions=useListWalletTransactions({limit:8}),habits=useListHabits(),create=useCreateReward(),update=useUpdateReward(),remove=useDeleteReward(),redeem=useRedeemReward(),qc=useQueryClient();
  const [editing,setEditing]=useState<Reward|true|null>(null),[title,setTitle]=useState(''),[emoji,setEmoji]=useState(rewardIcons[0]),[cost,setCost]=useState(50),[habitId,setHabitId]=useState('');
  const open=(r?:Reward)=>{setEditing(r||true);setTitle(r?.title||'');setEmoji(r?.emoji||rewardIcons[0]);setCost(r?.coinCost||50);setHabitId(r?.habitId?.toString()||'')};
  const refresh=()=>{qc.invalidateQueries({queryKey:getListRewardsQueryKey()});qc.invalidateQueries({queryKey:getGetWalletQueryKey()});qc.invalidateQueries({queryKey:getListWalletTransactionsQueryKey({limit:8})});qc.invalidateQueries({queryKey:getGetCurrentUserQueryKey()})};
  const save=(e:React.FormEvent)=>{e.preventDefault();const done=()=>{refresh();setEditing(null);toast.success('حُفظت مكافأتك')};if(editing!==true&&editing)update.mutate({rewardId:editing.id,data:{title,emoji,coinCost:cost}},{onSuccess:done,onError:()=>toast.error('تعذّر الحفظ')});else create.mutate({data:{title,emoji,coinCost:cost,habitId:habitId?Number(habitId):undefined}},{onSuccess:done,onError:()=>toast.error('تعذّر الحفظ')})};
  return <><PageHead overline="احتفِ بما تبنيه" title="المكافآت" desc="مكافآت حقيقية تختارها بنفسك، تستحقها مع كل خطوة." action={<AddButton onClick={()=>open()} label="مكافأة جديدة"/>}/><div className="grid lg:grid-cols-[1fr_2fr] gap-6 mb-10"><div className="bg-[#214e43] rounded-[24px] p-7 text-[#fff9e9]"><div className="flex gap-2 text-[#ebc185] text-sm font-bold"><Coins size={17}/> محفظتك</div><div className="text-5xl font-black mt-4">{wallet.data?.coins??0}<span className="text-base font-normal mr-2">عملة</span></div><div className="flex gap-5 text-sm text-[#c6daca] mt-7"><span>كسبت هذا الأسبوع: {wallet.data?.earnedThisWeek??0}</span><span>أنفقت: {wallet.data?.spentThisWeek??0}</span></div></div><div className="panel rounded-[24px] p-6"><SectionTitle label="حركة الرحلة" title="آخر المعاملات"/>{transactions.isLoading?<div className="skeleton h-16"/>:<div className="grid sm:grid-cols-2 gap-x-5">{transactions.data?.length?transactions.data.slice(0,6).map(t=><div className="flex justify-between border-b border-[#dddacb] py-2 text-sm" key={t.id}><span className="muted">{({checkin:'تسجيل عادة',streak_bonus:'مكافأة الاستمرار',streak_recovery:'استعادة سلسلة',reward_redemption:'استبدال مكافأة',item_purchase:'شراء عنصر',challenge_bonus:'مكافأة تحدٍ',manual:'تعديل الرصيد'} as Record<string,string>)[t.reason]}</span><b className={t.amount>0?'text-[#31765a]':'text-[#bc7455]'} dir="ltr">{t.amount>0?'+':''}{t.amount}</b></div>):<p className="muted text-sm">ستظهر حركة عملاتك هنا.</p>}</div>}</div></div>
    <SectionTitle label="اختر ما يسعدك" title="متجر مكافآتك"/>{rewards.isLoading?<Loading/>:rewards.isError?<ErrorBlock retry={()=>rewards.refetch()}/>:!rewards.data?.length?<Empty title="ما الذي تحب أن تكافئ نفسك به؟" desc="قد تكون استراحة لطيفة أو كتابًا جديدًا. أنت من يقرر." action={<AddButton onClick={()=>open()} label="أضف مكافأة"/>}/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{rewards.data.map((r,i)=><div key={r.id} className={`paper rounded-[22px] p-6 rise ${r.isRedeemed?'opacity-65':''}`} style={{animationDelay:`${i*50}ms`}}><div className="flex justify-between"><span className="text-4xl w-16 h-16 bg-[#f3ead8] rounded-2xl flex items-center justify-center">{r.emoji}</span><span className="badge h-fit"><Coins size={14}/>{r.coinCost}</span></div><h3 className="text-xl font-bold mt-5">{r.title}</h3><p className="text-sm muted mt-1">{r.isRedeemed?`استُبدلت ${r.redeemedAt?arDate(r.redeemedAt):''}`:'مكافأة تنتظرك على الطريق'}</p><div className="mt-6 flex gap-2">{r.isRedeemed?<span className="btn btn-light flex-1 !cursor-default"><Check size={16}/> استُبدلت</span>:<button className="btn flex-1" disabled={redeem.isPending||(wallet.data?.coins??0)<r.coinCost} onClick={()=>{if(confirm(`استبدال «${r.title}» مقابل ${r.coinCost} عملة؟`))redeem.mutate({rewardId:r.id},{onSuccess:()=>{refresh();toast.success('مكافأة تستحقّها!')},onError:()=>toast.error('تعذّر استبدال المكافأة')})}}>{(wallet.data?.coins??0)<r.coinCost?<Lock size={15}/>:<Gift size={15}/>} استبدال</button>}<button className="btn btn-light !px-3" aria-label="تعديل المكافأة" onClick={()=>open(r)}><Pencil size={15}/></button><button className="btn btn-light !px-3" aria-label="حذف المكافأة" onClick={()=>{if(confirm('حذف هذه المكافأة؟'))remove.mutate({rewardId:r.id},{onSuccess:()=>{refresh();toast.success('حُذفت المكافأة')},onError:()=>toast.error('تعذّر الحذف')})}}><Trash2 size={15}/></button></div></div>)}</div>}
    {editing&&<Modal title={editing===true?'مكافأة جديدة':'تعديل المكافأة'} onClose={()=>setEditing(null)}><form onSubmit={save}><Field label="ما المكافأة؟"><input className="field" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="نزهة، كتاب، وقت راحة..."/></Field><div className="flex flex-wrap gap-2 mb-5">{rewardIcons.map(x=><button type="button" key={x} onClick={()=>setEmoji(x)} className={`w-11 h-11 rounded-xl text-xl border ${emoji===x?'bg-[#e8c58e] border-[#b3885a]':'bg-[#f6eee1]'}`}>{x}</button>)}</div><Field label="التكلفة بالعملات"><input className="field" type="number" min="1" value={cost} onChange={e=>setCost(Number(e.target.value))}/></Field>{editing===true&&<Field label="اربطها بعادة (اختياري)"><select className="field" value={habitId} onChange={e=>setHabitId(e.target.value)}><option value="">رحلتي عمومًا</option>{habits.data?.map(h=><option value={h.id} key={h.id}>{h.title}</option>)}</select></Field>}<button className="btn w-full" disabled={create.isPending||update.isPending}>حفظ المكافأة</button></form></Modal>}
  </>;
}
export function JourneyPage(){
  const journey=useGetJourneyProgress(),character=useGetMyCharacter(),catalog=useListCharacterCatalog(),purchase=usePurchaseCharacterItem(),equip=useEquipCharacterItem(),qc=useQueryClient();
  const [slot,setSlot]=useState('الكل');const refresh=()=>{qc.invalidateQueries({queryKey:getListCharacterCatalogQueryKey()});qc.invalidateQueries({queryKey:getGetMyCharacterQueryKey()});qc.invalidateQueries({queryKey:getGetWalletQueryKey()});qc.invalidateQueries({queryKey:getGetCurrentUserQueryKey()})};
  const slots:Record<string,string>={outfit:'ملابس',hat:'قبعات',accessory:'إكسسوارات',pet:'رفقاء',background:'خلفيات'};
  return <><PageHead overline="كل خطوة ترسم طريقًا" title="رحلتي" desc="انظر إلى الطريق الذي قطعته، وإلى المحطات التي تنتظرك."/><div className="grid lg:grid-cols-[1fr_.72fr] gap-6 mb-12"><div className="relative rounded-[28px] overflow-hidden min-h-[360px] bg-[#d9e3cb]"><img src={`${import.meta.env.BASE_URL}journey-landscape.png`} className="absolute inset-0 w-full h-full object-cover" alt="منظر طريق الرحلة"/><div className="absolute inset-0 bg-gradient-to-l from-[#e6e8d5d9] to-transparent"/><div className="relative p-8 md:p-10 max-w-[450px]"><span className="eyebrow">موقعك الآن</span><h2 className="text-4xl font-black mt-3">المستوى {journey.data?.level??1}</h2><p className="mt-3 text-[#466b59]">الخطوات التي قطعتها لا تختفي. إنها تصنع طريقك.</p><div className="mt-8 bg-[#fffaeda9] rounded-2xl p-4"><div className="flex justify-between font-bold text-sm"><span>نحو المستوى التالي</span><span>{journey.data?.xp??0} / {journey.data?.xpToNextLevel??0}</span></div><div className="h-2 bg-[#d8d9ba] rounded-full mt-3"><div className="h-full bg-[#245448] rounded-full" style={{width:`${Math.min(100,((journey.data?.xp??0)/(journey.data?.xpToNextLevel||1))*100)}%`}}/></div></div></div></div><div className="rounded-[28px] bg-[#214e43] text-[#fff9e8] p-8 flex flex-col"><span className="text-[#edbd83] text-sm font-bold">رفيق رحلتك</span><div className="my-auto text-center py-7"><div className="w-32 h-32 mx-auto rounded-full bg-[#3c725e] border-[7px] border-[#ffffff1a] flex items-center justify-center text-6xl">🧭</div><div className="mt-5 flex justify-center gap-2">{character.data?.equippedItems.map(x=><span title={x.name} key={x.id} className="w-10 h-10 bg-[#ffffff25] rounded-full flex items-center justify-center text-xl">{x.emoji}</span>)}</div></div><p className="text-sm text-[#c4d8c8] text-center">زيّن شخصيتك بما تكسبه على الطريق.</p></div></div>
    <div className="grid lg:grid-cols-[.9fr_1.1fr] gap-9"><div><SectionTitle label="الطريق أمامك" title="محطات الرحلة"/>{journey.isLoading?<Loading/>:journey.isError?<ErrorBlock retry={()=>journey.refetch()}/>:<div className="relative border-r-2 border-dashed border-[#c8d4be] mr-5 space-y-6">{journey.data?.milestones.map((m,i)=><div key={m.id} className="relative pr-8 rise" style={{animationDelay:`${i*80}ms`}}><div className={`absolute -right-[18px] top-3 w-9 h-9 rounded-full border-4 border-[#f7f1e5] flex items-center justify-center ${m.reached?'bg-[#32765a] text-white':'bg-[#dedfd2]'}`}>{m.reached?<Check size={15}/>:<Lock size={13}/>}</div><div className={`paper rounded-2xl p-5 ${!m.reached?'opacity-70':''}`}><div className="flex items-center gap-3"><span className="text-2xl">{m.emoji}</span><div><div className="eyebrow">المستوى {m.levelRequired}</div><h3 className="font-bold text-lg">{m.title}</h3></div></div><p className="muted text-sm mt-3">{m.description}</p><span className="badge mt-3">+{m.rewardCoins} عملة</span></div></div>)}</div>}</div><div><SectionTitle label="كل ما يرافقك" title="خزانة الشخصية"/><div className="flex flex-wrap gap-2 mb-5">{['الكل',...Object.keys(slots)].map(s=><button key={s} className={`rounded-full px-4 py-2 text-sm ${slot===s?'bg-[#245448] text-white':'bg-[#e9e4d7]'}`} onClick={()=>setSlot(s)}>{slots[s]||s}</button>)}</div>{catalog.isLoading?<Loading/>:catalog.isError?<ErrorBlock retry={()=>catalog.refetch()}/>:!catalog.data?.length?<Empty title="الخزانة لم تُفتح بعد" desc="ستظهر هنا العناصر التي ترافق شخصيتك."/>:<div className="grid sm:grid-cols-2 gap-3">{catalog.data.filter(x=>slot==='الكل'||x.slot===slot).map(item=><div key={item.id} className="paper rounded-2xl p-4 flex items-center gap-3"><div className="w-14 h-14 shrink-0 rounded-xl bg-[#e9eadb] flex items-center justify-center text-3xl">{item.emoji}</div><div className="flex-1 min-w-0"><strong className="block truncate">{item.name}</strong><span className="text-xs muted">{slots[item.slot]}</span></div><button disabled={purchase.isPending||equip.isPending||item.equipped} className={`text-xs font-bold rounded-lg px-3 py-2 ${item.equipped?'bg-[#e8eee5] text-[#3b795a]':'bg-[#245448] text-white'}`} onClick={()=>{if(item.owned)equip.mutate({itemId:item.id},{onSuccess:()=>{refresh();toast.success('أصبح العنصر معك')},onError:()=>toast.error('تعذّر تجهيز العنصر')});else purchase.mutate({itemId:item.id},{onSuccess:()=>{refresh();toast.success('عنصر جديد في خزانتك!')},onError:()=>toast.error('عملاتك لا تكفي أو تعذّر الشراء')})}}>{item.equipped?'مجهّز':item.owned?'تجهيز':`${item.coinCost} عملة`}</button></div>)}</div>}</div></div>
  </>;
}