import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useListRewards,useCreateReward,useUpdateReward,useDeleteReward,useRedeemReward,useGetWallet,useListWalletTransactions,useListHabits,getListRewardsQueryKey,getGetWalletQueryKey,getListWalletTransactionsQueryKey,getGetCurrentUserQueryKey,getGetMyCharacterQueryKey,getGetDashboardTodayQueryKey,type Reward } from '@workspace/api-client-react';
import { toast } from 'sonner';
import { Coins, Gift, Pencil, Trash2, Check, Lock } from 'lucide-react';
import { PageHead, SectionTitle, Field, Modal, Empty, Loading, ErrorBlock, AddButton, arDate } from '@/components/journey-ui';

const rewardIcons=['🎁','☕','🎬','📚','🌷','🍰','🎟️','🧳'];
export function RewardsPage(){
  const rewards=useListRewards(),wallet=useGetWallet(),transactions=useListWalletTransactions({limit:8}),habits=useListHabits(),create=useCreateReward(),update=useUpdateReward(),remove=useDeleteReward(),redeem=useRedeemReward(),qc=useQueryClient();
  const [editing,setEditing]=useState<Reward|true|null>(null),[title,setTitle]=useState(''),[emoji,setEmoji]=useState(rewardIcons[0]),[cost,setCost]=useState(50),[habitId,setHabitId]=useState('');
  const open=(r?:Reward)=>{setEditing(r||true);setTitle(r?.title||'');setEmoji(r?.emoji||rewardIcons[0]);setCost(r?.coinCost||50);setHabitId(r?.habitId?.toString()||'')};
  const refresh=()=>{qc.invalidateQueries({queryKey:getListRewardsQueryKey()});qc.invalidateQueries({queryKey:getGetWalletQueryKey()});qc.invalidateQueries({queryKey:getListWalletTransactionsQueryKey({limit:8})});qc.invalidateQueries({queryKey:getGetCurrentUserQueryKey()});qc.invalidateQueries({queryKey:getGetMyCharacterQueryKey()});qc.invalidateQueries({queryKey:getGetDashboardTodayQueryKey()})};
  const save=(e:React.FormEvent)=>{e.preventDefault();const done=()=>{refresh();setEditing(null);toast.success('حُفظت مكافأتك')};if(editing!==true&&editing)update.mutate({rewardId:editing.id,data:{title,emoji,coinCost:cost}},{onSuccess:done,onError:()=>toast.error('تعذّر الحفظ')});else create.mutate({data:{title,emoji,coinCost:cost,habitId:habitId?Number(habitId):undefined}},{onSuccess:done,onError:()=>toast.error('تعذّر الحفظ')})};
  return <><PageHead overline="احتفِ بما تبنيه" title="المكافآت" desc="مكافآت حقيقية تختارها بنفسك، تستحقها مع كل خطوة." action={<AddButton onClick={()=>open()} label="مكافأة جديدة"/>}/><div className="grid lg:grid-cols-[1fr_2fr] gap-6 mb-10"><div className="bg-[#214e43] rounded-[24px] p-7 text-[#fff9e9]"><div className="flex gap-2 text-[#ebc185] text-sm font-bold"><Coins size={17}/> محفظتك</div><div className="text-5xl font-black mt-4">{wallet.data?.coins??0}<span className="text-base font-normal mr-2">عملة</span></div><div className="flex gap-5 text-sm text-[#c6daca] mt-7"><span>كسبت هذا الأسبوع: {wallet.data?.earnedThisWeek??0}</span><span>أنفقت: {wallet.data?.spentThisWeek??0}</span></div></div><div className="panel rounded-[24px] p-6"><SectionTitle label="حركة الرحلة" title="آخر المعاملات"/>{transactions.isLoading?<div className="skeleton h-16"/>:<div className="grid sm:grid-cols-2 gap-x-5">{transactions.data?.length?transactions.data.slice(0,6).map(t=><div className="flex justify-between border-b border-[#dddacb] py-2 text-sm" key={t.id}><span className="muted">{({checkin:'تسجيل عادة',streak_bonus:'مكافأة الاستمرار',streak_recovery:'استعادة سلسلة',reward_redemption:'استبدال مكافأة',item_purchase:'شراء عنصر',challenge_bonus:'مكافأة تحدٍ',manual:'تعديل الرصيد'} as Record<string,string>)[t.reason]}</span><b className={t.amount>0?'text-[#31765a]':'text-[#bc7455]'} dir="ltr">{t.amount>0?'+':''}{t.amount}</b></div>):<p className="muted text-sm">ستظهر حركة عملاتك هنا.</p>}</div>}</div></div>
    <SectionTitle label="اختر ما يسعدك" title="متجر مكافآتك"/>{rewards.isLoading?<Loading/>:rewards.isError?<ErrorBlock retry={()=>rewards.refetch()}/>:!rewards.data?.length?<Empty title="ما الذي تحب أن تكافئ نفسك به؟" desc="قد تكون استراحة لطيفة أو كتابًا جديدًا. أنت من يقرر." action={<AddButton onClick={()=>open()} label="أضف مكافأة"/>}/>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{rewards.data.map((r,i)=><div key={r.id} className={`paper rounded-[22px] p-6 rise ${r.isRedeemed?'opacity-65':''}`} style={{animationDelay:`${i*50}ms`}}><div className="flex justify-between"><span className="text-4xl w-16 h-16 bg-[#f3ead8] rounded-2xl flex items-center justify-center">{r.emoji}</span><span className="badge h-fit"><Coins size={14}/>{r.coinCost}</span></div><h3 className="text-xl font-bold mt-5">{r.title}</h3><p className="text-sm muted mt-1">{r.isRedeemed?`استُبدلت ${r.redeemedAt?arDate(r.redeemedAt):''}`:'مكافأة تنتظرك على الطريق'}</p><div className="mt-6 flex gap-2">{r.isRedeemed?<span className="btn btn-light flex-1 !cursor-default"><Check size={16}/> استُبدلت</span>:<button className="btn flex-1" disabled={redeem.isPending||(wallet.data?.coins??0)<r.coinCost} onClick={()=>{if(confirm(`استبدال «${r.title}» مقابل ${r.coinCost} عملة؟`))redeem.mutate({rewardId:r.id},{onSuccess:()=>{refresh();toast.success('مكافأة تستحقّها!')},onError:()=>toast.error('تعذّر استبدال المكافأة')})}}>{(wallet.data?.coins??0)<r.coinCost?<Lock size={15}/>:<Gift size={15}/>} استبدال</button>}<button className="btn btn-light !px-3" aria-label="تعديل المكافأة" onClick={()=>open(r)}><Pencil size={15}/></button><button className="btn btn-light !px-3" aria-label="حذف المكافأة" onClick={()=>{if(confirm('حذف هذه المكافأة؟'))remove.mutate({rewardId:r.id},{onSuccess:()=>{refresh();toast.success('حُذفت المكافأة')},onError:()=>toast.error('تعذّر الحذف')})}}><Trash2 size={15}/></button></div></div>)}</div>}
    {editing&&<Modal title={editing===true?'مكافأة جديدة':'تعديل المكافأة'} onClose={()=>setEditing(null)}><form onSubmit={save}><Field label="ما المكافأة؟"><input className="field" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="نزهة، كتاب، وقت راحة..."/></Field><div className="flex flex-wrap gap-2 mb-5">{rewardIcons.map(x=><button type="button" key={x} onClick={()=>setEmoji(x)} className={`w-11 h-11 rounded-xl text-xl border ${emoji===x?'bg-[#e8c58e] border-[#b3885a]':'bg-[#f6eee1]'}`}>{x}</button>)}</div><Field label="التكلفة بالعملات"><input className="field" type="number" min="1" value={cost} onChange={e=>setCost(Number(e.target.value))}/></Field>{editing===true&&<Field label="اربطها بعادة (اختياري)"><select className="field" value={habitId} onChange={e=>setHabitId(e.target.value)}><option value="">رحلتي عمومًا</option>{habits.data?.map(h=><option value={h.id} key={h.id}>{h.title}</option>)}</select></Field>}<button className="btn w-full" disabled={create.isPending||update.isPending}>حفظ المكافأة</button></form></Modal>}
  </>;
}
export { CharacterPage as JourneyPage } from './character';
